### ISSUE TITLE
Bug: Fresh installation is missing numpy

### ISSUE THREAD

**Issue by janvainer** [danpovey/lilcom#24]
Hi, when installing this package in a fresh virtual environment, the following error eccurs:

```
  Downloading https://files.pythonhosted.org/packages/8b/53/43f601d93e9f33da1c9d6909c1bf94390666726dbd2d18e76c377a5a1a9a/lilcom-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-szfvvzdg/lilcom/setup.py", line 26, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
```
By installing numpy beforehand, it is then possible to install lilcom. Could this be mentioned in the README?

**Comment by csukuangfj** [comment]
It is mentioned in `setup.py`:

https://github.com/danpovey/lilcom/blob/7feb4b22084b0952b5b889a348b650d2685ffb51/setup.py#L59

It would be great if PyPI contains prebuilt wheel packages, so that `pip install` will install `numpy` automatically.

**Comment by danpovey** [comment]
OK.

**Comment by danpovey** [comment]
Actually, can you LMK specifically what I have to do?
Previously I was doing:
  python3 ./setup.py sdist;   twine upload  dist/*
For a binary distribution I think I'd need to compile it on a variety of
platforms (it contains C++ code).

**Comment by csukuangfj** [comment]
@danpovey 
There is something called manylinux. See https://github.com/pypa/manylinux

In summary: a wheel compiled for manylinux can run not only on Ubuntu, Debian, but also on other
Linuxes, like CentOS, Redhat, etc. That is the meaning of `many`.  This kind of wheel uses only
a limited set of C APIs that are supported by GLIBC on many Linux OSes.

**Comment by csukuangfj** [comment]
`manylinux` is not used for k2, since k2 depends on PyTorch, but PyTorch does not provide a wheel for manylinux after
version 1.5.0 or 1.3.0, I cannot remember the exact version.

**Comment by csukuangfj** [comment]
BTW: PyPI supports manylinux. So if you can build a manylinux wheel, it can be uploaded to PyPI so that
others can use `pip install lilcom` to install it instead of compiling lilcom from source.

**Comment by csukuangfj** [comment]
I would like to help if you do not have time.

**Comment by danpovey** [comment]
It would be great if you could help.
But I don't understand why pip can't know to install NumPy as a dependency
of lilcom if lilcom is to be built from source?  I don't see what's so
difficult about that.
Building from source will tend to give more efficient code, which might be
a significant consideration.

**Comment by csukuangfj** [comment]
I just tried 

```bash
pip install git+https://github.com/danpovey/lilcom
```
and got the same error message as the one posted by @janvainer.

I think the problem is that `pip install` will try to run `setup.py`, but `setup.py` assumes that
`numpy` has already been installed.

**Comment by danpovey** [comment]
Maybe we need to create a requirements.txt?

**Comment by csukuangfj** [comment]
> Maybe we need to create a requirements.txt?

I tried it locally once again with a requirements.txt inside the project but it does not help. It has the same error.

**Comment by danpovey** [comment]
I think the problem may be that the setup.py calls numpy.get_include(), and
it imports numpy.

**Comment by danpovey** [comment]
See if you can find the answer from here
https://stackoverflow.com/questions/54117786/add-numpy-get-include-argument-to-setuptools-without-preinstalled-numpy
