### ISSUE TITLE
In file included from lilcom/lilcom_extension.cc:15: In file included from lilcom/compression.h:6: lilcom/int_stream.h:7:10: fatal error: 'vector' file not found #include <vector>          ^~~~~~~~ 1 error generated. error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by wuxiaobo** [danpovey/lilcom#29]
python3 setup.py install --user
running install
error: [Errno 13] Permission denied: '/Users/wuxb/Library/Python/3.7/lib'
wuxb@wuxbdeMacBook-Pro lilcom % sudo python3 setup.py install --user
Password:
running install
running bdist_egg
running egg_info
writing lilcom.egg-info/PKG-INFO
writing dependency_links to lilcom.egg-info/dependency_links.txt
writing requirements to lilcom.egg-info/requires.txt
writing top-level names to lilcom.egg-info/top_level.txt
reading manifest file 'lilcom.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lilcom.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
running build_ext
building 'lilcom.lilcom_extension' extension
gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c lilcom/lilcom_extension.cc -o build/temp.macosx-10.6-intel-3.7/lilcom/lilcom_extension.o -g -Wall -UNDEBUG -Wno-c++11-compat-deprecated-writable-strings
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from lilcom/lilcom_extension.cc:15:
In file included from lilcom/compression.h:6:
lilcom/int_stream.h:7:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

gcc --version                                    
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by danpovey** [comment]
I'm having trouble understanding what is going wrong here.  It should
recognize that it's compiling C++ by virtue of the file extension (.cc).

Try changing the line in setup.py that  defines extra_compile_args to the
following:
 extra_compile_args=["-g", "-stdlib=c++", "-Wall", "-UNDEBUG",
"-Wno-c++11-compat-deprecated-writable-strings"],
... but it is very odd that that would be necessary.
Do you know of anything  unusual about your toolchain?  Problems building
other packages?

**Comment by danpovey** [comment]
Wait, now I see you're running as root.  That's not right.  You should just
jump to using sudo any time you get a permission problem.
Doing that kind of thing is likely to screw up your computer pretty quick,
you'll have files owned by root owned where they shouldn't be.
Anyway, installing as --user with sudo may be trying to install it in
root's homedir or something.

**Comment by danpovey** [comment]
Likely problem is that /Users/wuxb/Library/Python/3.7/lib is owned by root and not readable by you because you made the same mistake before, using sudo when you should not.

**Comment by danpovey** [comment]
` chown -R your_username /Users/wuxb/Library/Python/3.7 `
may help

**Comment by wuxiaobo** [comment]
i use user_name 

python3 setup.py install     
running install
running bdist_egg
running egg_info
writing lilcom.egg-info/PKG-INFO
writing dependency_links to lilcom.egg-info/dependency_links.txt
writing requirements to lilcom.egg-info/requires.txt
writing top-level names to lilcom.egg-info/top_level.txt
reading manifest file 'lilcom.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lilcom.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
running build_ext
building 'lilcom.lilcom_extension' extension
gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c lilcom/lilcom_extension.cc -o build/temp.macosx-10.6-intel-3.7/lilcom/lilcom_extension.o -g -Wall -UNDEBUG -Wno-c++11-compat-deprecated-writable-strings
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from lilcom/lilcom_extension.cc:15:
In file included from lilcom/compression.h:6:
lilcom/int_stream.h:7:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1
@danpovey Daniel Povey

**Comment by wuxiaobo** [comment]
i use root user ,some error
wuxb@wuxbdeMacBook-Pro lilcom % sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing lilcom.egg-info/PKG-INFO
writing dependency_links to lilcom.egg-info/dependency_links.txt
writing requirements to lilcom.egg-info/requires.txt
writing top-level names to lilcom.egg-info/top_level.txt
reading manifest file 'lilcom.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lilcom.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-intel/egg
running install_lib
running build_py
running build_ext
building 'lilcom.lilcom_extension' extension
gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c lilcom/lilcom_extension.cc -o build/temp.macosx-10.6-intel-3.7/lilcom/lilcom_extension.o -g -Wall -UNDEBUG -Wno-c++11-compat-deprecated-writable-strings
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from lilcom/lilcom_extension.cc:15:
In file included from lilcom/compression.h:6:
lilcom/int_stream.h:7:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1
@danpovey

**Comment by wuxiaobo** [comment]
@danpovey  I user pip3 install lilcom  ,then some error.
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting lilcom
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='mirrors.aliyun.com', port=80): Read timed out. (read timeout=15)")': /pypi/simple/lilcom/
  Downloading http://mirrors.aliyun.com/pypi/packages/46/78/9605e17af46a789747544c66f69bcfba17d43ae12f7caeb82f10bbd3fbd5/lilcom-1.1.1.tar.gz
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from lilcom) (1.19.4)
Building wheels for collected packages: lilcom
  Building wheel for lilcom (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-wheel-9of2btyw --python-tag cp37
       cwd: /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/
  Complete output (22 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-3.7
  creating build/lib.macosx-10.6-intel-3.7/lilcom
  copying lilcom/lilcom_interface.py -> build/lib.macosx-10.6-intel-3.7/lilcom
  copying lilcom/__init__.py -> build/lib.macosx-10.6-intel-3.7/lilcom
  running build_ext
  building 'lilcom.lilcom_extension' extension
  creating build/temp.macosx-10.6-intel-3.7
  creating build/temp.macosx-10.6-intel-3.7/lilcom
  gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c lilcom/lilcom_extension.cc -o build/temp.macosx-10.6-intel-3.7/lilcom/lilcom_extension.o -g -Wall -UNDEBUG -Wno-c++11-compat-deprecated-writable-strings
  clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from lilcom/lilcom_extension.cc:15:
  In file included from lilcom/compression.h:6:
  lilcom/int_stream.h:6:10: fatal error: 'vector' file not found
  #include <vector>
           ^~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for lilcom
  Running setup.py clean for lilcom
Failed to build lilcom
Installing collected packages: lilcom
  Running setup.py install for lilcom ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-record-uy9bpv7w/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/
    Complete output (22 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.7
    creating build/lib.macosx-10.6-intel-3.7/lilcom
    copying lilcom/lilcom_interface.py -> build/lib.macosx-10.6-intel-3.7/lilcom
    copying lilcom/__init__.py -> build/lib.macosx-10.6-intel-3.7/lilcom
    running build_ext
    building 'lilcom.lilcom_extension' extension
    creating build/temp.macosx-10.6-intel-3.7
    creating build/temp.macosx-10.6-intel-3.7/lilcom
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c lilcom/lilcom_extension.cc -o build/temp.macosx-10.6-intel-3.7/lilcom/lilcom_extension.o -g -Wall -UNDEBUG -Wno-c++11-compat-deprecated-writable-strings
    clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from lilcom/lilcom_extension.cc:15:
    In file included from lilcom/compression.h:6:
    lilcom/int_stream.h:6:10: fatal error: 'vector' file not found
    #include <vector>
             ^~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-iwwzc8br/lilcom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-record-uy9bpv7w/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by danpovey** [comment]
I think you have ruined your mac installation by using 'sudo' when you
shouldn't be using sudo.  You may have to try to uninstall and reinstall
some things, or change file ownership everywhere at the very least.

**Comment by wuxiaobo** [comment]
😭   you are sure?

**Comment by csukuangfj** [comment]
> 😭 you are sure?


Maybe you can verify it by installing some other packages, e.g., `pip install kaldialign`.
If it still fails, it's very likely that there are some problems with your mac.

**Comment by csukuangfj** [comment]
Also, can you compile a `hello world` c++ program?

**Comment by danpovey** [comment]
I'd try uninstalling and reinstalling XCode, if mac will let you.

**Comment by wuxiaobo** [comment]
g++ helloworld.cpp -o helloworld
./helloworld 
Hello, world!

**Comment by wuxiaobo** [comment]
> > 😭 you are sure?
> 
> Maybe you can verify it by installing some other packages, e.g., `pip install kaldialign`.
> If it still fails, it's very likely that there are some problems with your mac.

 pip3 install kaldialign
some error
 ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-q6hfu333/kaldialign/setup.py'"'"'; __file__='"'"'/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-q6hfu333/kaldialign/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-record-5ic043ht/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-q6hfu333/kaldialign/
    Complete output (19 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.7
    creating build/lib.macosx-10.6-intel-3.7/extensions
    copying extensions/__init__.py -> build/lib.macosx-10.6-intel-3.7/extensions
    running build_ext
    building 'kaldialign' extension
    creating build/temp.macosx-10.6-intel-3.7
    creating build/temp.macosx-10.6-intel-3.7/extensions
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-q6hfu333/kaldialign/extensions -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c extensions/align.cpp -o build/temp.macosx-10.6-intel-3.7/extensions/align.o -std=c++11 -Wno-register -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char -stdlib=libc++ -mmacosx-version-min=10.7
    gcc -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch i386 -arch x86_64 -g -I/private/var/folders/y0/dntzz2g93b54yr3c200ccvy80000gn/T/pip-install-q6hfu333/kaldialign/extensions -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c extensions/kaldi_align.cpp -o build/temp.macosx-10.6-intel-3.7/extensions/kaldi_align.o -std=c++11 -Wno-register -Wno-unused-function -Wno-unused-local-typedefs -funsigned-char -stdlib=libc++ -mmacosx-version-min=10.7
    g++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.7/extensions/align.o build/temp.macosx-10.6-intel-3.7/extensions/kaldi_align.o -o build/lib.macosx-10.6-intel-3.7/kaldialign.cpython-37m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'g++' failed with exit status 1

**Comment by csukuangfj** [comment]
Then can you create a virtual environment for python to install packages? For example, with https://virtualenv.pypa.io/en/latest/
