### ISSUE TITLE
 Build lilcom failed. Please check the error message. -- solved!

### ISSUE THREAD

**Issue by Amoolya-projects** [danpovey/lilcom#46]
I am trying to install lhotse
and I am getting this error:
 Build lilcom failed. Please check the error message.

Code I used:
pip install git+https://github.com/lhotse-speech/lhotse

Please help.

**Comment by pzelasko** [comment]
Please post the full error log from the installation, it should have some pointers what happened.

**Comment by Amoolya-projects** [comment]
> Please post the full error log from the installation, it should have some pointers what happened.

Building wheels for collected packages: lilcom
  Building wheel for lilcom (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]

 Exception:
      Build lilcom failed. Please check the error message.
      You can ask for help by creating an issue on GitHub.

      Click:
          https://github.com/danpovey/lilcom/issues/new

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lilcom
  Running setup.py clean for lilcom
Failed to build lilcom
Installing collected packages: lilcom, cytoolz, cffi, SoundFile, lhotse
  Running setup.py install for lilcom ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lilcom did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]

Exception:
      Build lilcom failed. Please check the error message.
      You can ask for help by creating an issue on GitHub.

      Click:
          https://github.com/danpovey/lilcom/issues/new

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lilcom

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Is this helpful?

**Comment by csukuangfj** [comment]
Please post all the logs.

**Comment by Amoolya-projects** [comment]
Thank you for the quick replies. 
This error got solved. 

Cmake was not installed properly. So uninstalled and reinstalled the cmake. 

To install cmake:
sudo snap install cmake
