### ISSUE TITLE
Lilcom numpy version requirements.

### ISSUE THREAD

**Issue by videodanchik** [danpovey/lilcom#51]
`Lilcom` restricts `numpy<1.23` for python 3.10 see https://github.com/danpovey/lilcom/blob/6860da1fd12c00696096a6616571de89a54d6b36/setup.py#L48 Is there any particular reason for this, because it dumps my `numpy` version during my docker environment build when pip resolves version conflicts?

**Comment by csukuangfj** [comment]
It's to fix errors from GitHub actions.

You can change the version requirement as long as it does not cause issues for you.

**Comment by videodanchik** [comment]
Thanks, @csukuangfj, the problem comes with the fact that I'm working in a docker container that's built upon my DockerFile that includes a line like `RUN pip install --no-cache-dir -r requirements.txt` and `lhotse` pulls `lilcom` and lilcom dumps `numpy` version  that I want to be `1.23`. Is there any way how the problem can be solved by removing this restriction somehow, I will do it myself if you share some context with me, what do you think?

**Comment by csukuangfj** [comment]
> Is there any way how the problem can be solved by removing this restriction somehow

The constraint is added in https://github.com/danpovey/lilcom/pull/37

You can replace
https://github.com/danpovey/lilcom/blob/6860da1fd12c00696096a6616571de89a54d6b36/setup.py#L46-L49
with
```
"numpy"
```

**Comment by videodanchik** [comment]
Closed by https://github.com/danpovey/lilcom/pull/52
