### ISSUE TITLE
requirements, why?

### ISSUE THREAD

**Issue by danpovey** [danpovey/lilcom#57]
@csukuangfj why does our requirements file have detailed requirements on the numpy and associated python versions?

 "Cython; sys_platform=='win32' and python_version >= '3.10'",
    "numpy<=1.19.5; python_version >= '3.6' and python_version < '3.7'",
    "numpy<=1.21.6; python_version >= '3.7' and python_version < '3.8'",
    "numpy<1.23.0; python_version >= '3.8' and python_version < '3.10'",
    "numpy; python_version >= '3.10'",

Is this just what we've tested? I think we are basically only using the dlpack or whatever, no detailed features, I think?
It seems to sometimes cause problems e.g. when lhotse wants to update numpy, and it suggests a version that isn't within this requirements matrix.

**Comment by csukuangfj** [comment]
> Is this just what we've tested?

Because it has errors when using GitHub actions to compile it. 

I am retesting it and see if we can remove that constraint.

**Comment by csukuangfj** [comment]
Should be fixed by #58 
Please use
```
pip install lilcom>=1.7
```
to install the latest version.
